name: Auto PURGE Every 5 Seconds

on:
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  purge:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Max ~5 jam 50 menit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make purge.sh executable
        run: chmod +x purge.sh

      - name: Run PURGE loop
        run: ./purge.sh
